# Generated by Django 4.2.6 on 2023-10-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camera',
            new_name='Camara',
        ),
    ]
