# Generated by Django 4.2.6 on 2023-11-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0002_rename_camera_camara'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='resolucion',
            field=models.CharField(default=720, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camara',
            name='rotacion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
