# Generated by Django 4.2.6 on 2023-11-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0003_camara_resolucion_camara_rotacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='resolucion',
            field=models.IntegerField(default=720),
        ),
        migrations.AlterField(
            model_name='camara',
            name='rotacion',
            field=models.IntegerField(default=0),
        ),
    ]
