# Generated by Django 4.2.6 on 2023-11-20 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0004_alter_camara_resolucion_alter_camara_rotacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='angulo_de_vision',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='camara',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='camara',
            name='tipo',
            field=models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=20),
        ),
    ]
