# Generated by Django 4.2.6 on 2023-11-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0006_camara_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='nombre',
            field=models.CharField(default='SinNombre', max_length=100),
        ),
    ]
