# Generated by Django 4.2.6 on 2023-11-22 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0007_camara_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sensor', max_length=100)),
                ('tipo', models.CharField(choices=[('presencia', 'Presencia'), ('puertas y ventanas', 'Puertas y Ventanas'), ('movimiento', 'Moviemiento')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='camara',
            name='nombre',
            field=models.CharField(default='Camara', max_length=100),
        ),
    ]
