# Generated by Django 4.2.6 on 2023-11-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0008_sensores_alter_camara_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensores',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='sensores/'),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='tipo',
            field=models.CharField(choices=[('presencia', 'Presencia'), ('puertas y ventanas', 'Puertas y Ventanas'), ('movimiento', 'Movimiento')], max_length=20),
        ),
    ]
