# Generated by Django 4.2.6 on 2023-12-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0010_camara_alcance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camara',
            old_name='alcance',
            new_name='alcance_cm',
        ),
    ]
