# Generated by Django 4.2.6 on 2023-11-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disenoPlanos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensores',
            new_name='Planos',
        ),
    ]
