# Generated by Django 4.2.6 on 2023-12-12 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disenoPlanos', '0002_rename_sensores_planos'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
