# Generated by Django 4.2.6 on 2023-12-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posicionCamaras', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='CambiarHardware',
        ),
        migrations.DeleteModel(
            name='CambiarPlanos',
        ),
        migrations.DeleteModel(
            name='ExportarPDF',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
